#!/bin/bash

file=${1}

if [ -z "${file}" ]
then
	# The length of the string "${file}" is zero
	echo "Usage: mdspdf FILE"
	exit 1

fi

if [ ! -f "${file}.md" ]
then
	# There is no file named "${file}.md}
	echo "Missing file: ${file}.md"
	exit 1
fi

pandoc -o "${1}.pdf" "${1}.md"
